# Generated by Django 4.2.7 on 2023-12-23 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_vividuser_email_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='vividuser',
            name='verification_code',
            field=models.CharField(blank=True, max_length=6),
        ),
        migrations.AddField(
            model_name='vividuser',
            name='verification_token',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
