# Generated by Django 4.2.7 on 2023-12-23 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_vividuser_agreed_to_terms'),
    ]

    operations = [
        migrations.AddField(
            model_name='vividuser',
            name='account_type',
            field=models.CharField(choices=[('Influencer', 'Influencer'), ('Content Creator', 'Content Creator'), ('Organization', 'Organization')], default='Influencer', max_length=50),
        ),
    ]
