# Generated by Django 4.2.7 on 2023-12-23 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_vividuser_account_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vividuser',
            name='account_type',
            field=models.CharField(blank=True, choices=[('Influencer', 'Influencer'), ('Content Creator', 'Content Creator'), ('Organization', 'Organization')], default=None, max_length=50, null=True),
        ),
    ]
