# Generated by Django 4.2.7 on 2023-12-24 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_vividuser_profile_completed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vividuser',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='media/images/profile_pics/'),
        ),
    ]
