# Generated by Django 4.2.7 on 2023-12-24 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0003_hashtag'),
        ('users', '0008_alter_vividuser_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='vividuser',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female')], default=None, max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='vividuser',
            name='hashtags',
            field=models.ManyToManyField(related_name='users', to='social.hashtag'),
        ),
    ]
