# Generated by Django 4.2.7 on 2023-12-25 18:11

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_vividuser_gender_vividuser_hashtags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vividuser',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to=users.models.user_directory_path),
        ),
    ]
