# Generated by Django 4.2.7 on 2023-12-26 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_vividuser_social_links_vividuser_website_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vividuser',
            name='social_links',
        ),
        migrations.AddField(
            model_name='vividuser',
            name='facebook_link',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='vividuser',
            name='instagram_link',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='vividuser',
            name='linkedin_link',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='vividuser',
            name='tiktok_link',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='vividuser',
            name='x_link',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='vividuser',
            name='youtube_link',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
    ]
