# Generated by Django 4.2.7 on 2023-12-26 00:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_remove_vividuser_social_links_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vividuser',
            name='facebook_link',
        ),
        migrations.RemoveField(
            model_name='vividuser',
            name='instagram_link',
        ),
        migrations.RemoveField(
            model_name='vividuser',
            name='linkedin_link',
        ),
        migrations.RemoveField(
            model_name='vividuser',
            name='tiktok_link',
        ),
        migrations.RemoveField(
            model_name='vividuser',
            name='x_link',
        ),
        migrations.RemoveField(
            model_name='vividuser',
            name='youtube_link',
        ),
    ]
