# Generated by Django 4.2.7 on 2023-12-26 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_remove_vividuser_facebook_link_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vividuser',
            name='hashtags',
        ),
    ]
