# Generated by Django 4.2.7 on 2023-12-24 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hashtag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
    ]
