# Generated by Django 4.2.7 on 2023-12-26 00:10

from django.db import migrations, models
import social.models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0003_hashtag'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('url', models.URLField(max_length=255)),
                ('icon', models.ImageField(blank=True, upload_to=social.models.social_link_icon_directory_path)),
            ],
        ),
    ]
