# Generated by Django 4.2.7 on 2023-12-26 00:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_remove_vividuser_social_links_and_more'),
        ('social', '0004_sociallink'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SocialLink',
        ),
    ]
