# Generated by Django 4.2.7 on 2024-01-02 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0007_socialmediaplatform_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialmediaplatform',
            name='login_callback_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='socialmediaplatform',
            name='login_redirect_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
