# Generated by Django 4.2.7 on 2024-01-04 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0008_socialmediaplatform_login_callback_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialmediaprofile',
            name='access_token',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='socialmediaprofile',
            name='refresh_token',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='socialmediaprofile',
            name='token_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
