# Generated by Django 4.2.7 on 2024-01-04 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0009_socialmediaprofile_access_token_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialmediaprofile',
            name='account_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='socialmediaprofile',
            name='profile_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='socialmediaprofile',
            name='remote_profile_picture',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
