# Generated by Django 4.2.7 on 2023-11-22 22:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('content', '0001_initial'),
        ('social', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentplatformstatus',
            name='platform',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='social.socialmediaprofile'),
        ),
        migrations.AddField(
            model_name='content',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contents', to='social.socialmediaprofile'),
        ),
    ]
